apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx_config.conf: |
    server {
      listen 8080;

      location /api/v1/movies {
        proxy_pass http://{{ .Release.Name }}-helm-movie-service:8000/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://{{ .Release.Name }}-helm-cast-service:8000/api/v1/casts;
      }
    }
