apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-movie-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.movieService.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: movie-service
          image: "{{ .Values.movieService.image.repository }}:{{ .Values.movieService.image.tag }}"
          ports:
            - containerPort: {{ .Values.movieService.service.port }}
          volumeMounts:
            - name: volume-movie
              mountPath: /app
          env:
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
            - name: castService_HOST_URL
              value: http://castService:8000/api/v1/casts/
      volumes:
        - name: volume-movie

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-movie-db
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.movieDb.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: movie-db
          image: "{{ .Values.movieDb.image.repository }}:{{ .Values.movieDb.image.tag }}"
          ports:
            - containerPort: {{ .Values.movieDb.service.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.movieDb.environment.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.movieDb.environment.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.movieDb.environment.POSTGRES_DB }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-cast-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.castService.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.castService.image.repository }}:{{ .Values.castService.image.tag }}"
          ports:
            - containerPort: {{ .Values.castService.service.port }}
          volumeMounts:
            - name: volume-cast
              mountPath: /app
          env:
            - name: DATABASE_URI
              value: postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
      volumes:
        - name: volume-cast

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-cast-db
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.castDb.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cast-db
          image: "{{ .Values.castDb.image.repository }}:{{ .Values.castDb.image.tag }}"
          ports:
            - containerPort: {{ .Values.castDb.service.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.castDb.environment.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.castDb.environment.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.castDb.environment.POSTGRES_DB }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-nginx
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: {{ .Values.nginx.service.port }}
          volumeMounts:
            - name: volume-nginx
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: volume-nginx
