apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-movie-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.movieService.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: movie-service
          image: "{{ .Values.movieService.image.repository }}:{{ .Values.movieService.image.tag }}"
          command: ["uvicorn"]
          args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]
          ports:
            - containerPort: {{ .Values.movieService.service.port }}
          env:
          - name: DATABASE_URI
            value: postgresql://movie_db_username:movie_db_password@{{ .Release.Name }}-helm-movie-service/movie_db_dev
          - name: castService_HOST_URL
            value: http://{{ .Release.Name }}-helm-cast-service:{{ .Values.castService.service.port }}/api/v1/casts/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-cast-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.castService.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.castService.image.repository }}:{{ .Values.castService.image.tag }}"
          command: ["uvicorn"]
          args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]
          ports:
            - containerPort: {{ .Values.castService.service.port }}
          env:
            - name: DATABASE_URI
              value: postgresql://cast_db_username:cast_db_password@{{ .Release.Name }}-helm-cast-service/cast_db_dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-nginx
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: {{ .Values.nginx.service.port }}
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            items:
            - key: nginx_config.conf
              path: default.conf
