# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

movieService:
  replicaCount: 1
  image:
    repository: doriansechal/movie-service
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8001
    targetPort: 8000

movieDb:
  replicaCount: 1
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "12.1-alpine"
  service:
    type: ClusterIP
    port: 5432

castService:
  replicaCount: 1
  image:
    repository: doriansechal/cast-service
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8002
    targetPort: 8000

castDb:
  replicaCount: 1
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "12.1-alpine"
  service:
    type: ClusterIP
    port: 5432

nginx:
  replicaCount: 1
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: NodePort
    port: 8080

volume:
  name: storage
  accessMode: ReadWriteOnce
  storage: 5Gi
  storageClassName: local-path
