# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

movieService:
  image:
    repository: doriansechal/movie-service
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: ClusterIP
    port: 8001
  environment:
    DATABASE_URI: "postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev"

movieDb:
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "12.1-alpine"
  environment:
    POSTGRES_USER: movie_db_username
    POSTGRES_PASSWORD: movie_db_password
    POSTGRES_DB: movie_db_dev
  service:
    type: ClusterIP
    port: 5432

castService:
  image:
    repository: doriansechal/cast-service
    pullPolicy: IfNotPresent
    tag: ""
  
  service:
    type: ClusterIP
    port: 8002
  environment:
    DATABASE_URI: "postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev"

castDb:
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "12.1-alpine"
  environment:
    POSTGRES_USER: cast_db_username
    POSTGRES_PASSWORD: cast_db_password
    POSTGRES_DB: cast_db_dev
    service:
    type: ClusterIP
    port: 5433

nginx:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
